### ISSUE TITLE
"Heating To" not resolved

### ISSUE THREAD

**Issue by paullsoucy** [stelpro/Ki-ZigBee-Thermostat#4]
The issue has changed since the latest update of July13th.  The "Heating to " message does not go away once the set temp has been met. In fact when I change the mode from Comfort to Eco to Off, The Heating to message does not leave or change from Comfort Eco or Off, it hates from "Heating to xx" (set temp), "Heating to 63" (Eco equivalent) and "Heating to --" for off. The tile does not change color from Orange to Green. 
BTW. I copied the device handler code, saved, published, and tested, then rebooted hub and retested.  Same result as above.  Also I still do not have a set temp number between my up and down arrow.

**Comment by stelpro** [comment]
Are you refering to the zigbee or z-wave device handler?

**Comment by paullsoucy** [comment]
ZigBee Paul

**Comment by stelpro** [comment]
I don't fully understand what you experience as a bug.
Please give me more details and steps to reproduce.
Do you perform the mode change from the SmartThings app or from the physical device?

**Comment by paullsoucy** [comment]
I am using the device driver on my iPhone to change these modes.  I am not at the device as it is a remote location.  I am not using an automation to make any changes just the driver you modified yesterday. 
I tried to attach the screen shots but I am not sure if you can see them below.
![img_3662](https://user-images.githubusercontent.com/29361595/28211790-736851ec-686c-11e7-9aa7-0402ec4f23f6.PNG)
![img_3663](https://user-images.githubusercontent.com/29361595/28211792-737798be-686c-11e7-893a-e990d3764eec.PNG)
![img_3664](https://user-images.githubusercontent.com/29361595/28211791-7371c614-686c-11e7-9397-b41aa6350b0f.PNG)

**Comment by stelpro** [comment]
Yes, I do see the screenshots.

The device handler was mainly developed and tested with Android devices.
I managed to get an iPad, I will do some tests with it later.

**Comment by paullsoucy** [comment]
OK  Also, I just checked and the situation is the same on my iPad as well as iPhone. Good Luck.

**Comment by stelpro** [comment]
If you have the chance, test it on an Android device to see if you see the same behavior

**Comment by stelpro** [comment]
I confirm that the iOS device does not display the setpoint.
I have no clue why, this is dependent of the SmartThings app developer.
I can't do anything about it.
I did send an e-mail to the SmartThings staff...

When you change the setpoint, do you see the orange and green background color changing accordingly?

Is it only when the setpoint has been set, and the device heats for a while and reach the setpoint that you have an issue?
In that case, the Heating status is not sent right away, you may have to wait few minutes before the device sends the heating status to the hub.

**Comment by kevnord** [comment]
Paul, what 220v device did you use to control the power to your hot water heater? I want to add one to my cottage.

**Comment by paullsoucy** [comment]
Kevin,

They are still sold but I’m not sure if they are still made. They work well but sometimes if power is lost they need to be re-paired to the Smartthings network. Also, be sure to pay attention to the wiring diagram. To use it as a 2-pole switch you need to install jumpers across some terminals. 

Good luck. 
Paul

**Comment by miketmcse** [comment]
@paullsoucy I have the same issue with Zigbee version I just installed last night. Did @stelpro ever get back to you?
I don't think it is purely an IOS issue. I also have a ZWave version and using the same webCoRE piston to set both Thermostats based on location mode and I am using action tiles. I didn't pay much attention last night after I got the new Zigbee Thermostat installed and the Piston reconfigured, as I had other task to finish last night. This morning I left for work which triggers the Piston and it changed the Setpoint from 68 to 64 and now the Tile is showing Heating in Actiontiles (and is active like an accent or warn tile) instead of idle like the Zwave thermostat does. The Temperature is dropping based on remote sensors so I know it is working right but the Tiles in Actiontiles is wrong same as the device in Smartthings app in IOS. It like the Heating and Idle are reversed, I am not changing modes so I don't think that is relevant to the issue either. And before anyone ask I am copied the DH code from stelpro/Ki-ZigBee-Thermostat last night which was updated 2 months ago.

**Comment by stelpro** [comment]
Hi Mike,

As I stated above, it seems to me to be an iOS issue.
Our tests done with Android devices give good results and the DH is the same for Android and iOS.

See the code snippet below, you may see that if the heat demand is above 10%, the status is declared at “heating” otherwise it’s “idle”

            log.debug "HEAT DEMAND"
            map.name = "thermostatOperatingState"
            map.value = getModeMap()[descMap.value]
            if (descMap.value < "10")
            {
            	map.value = "idle"
            }
            else
            {
            	map.value = "heating"
            }
            sendEvent(name:"thermostatOperatingState", value:map.value)

**Comment by miketmcse** [comment]
Turns out my ST Hub was not communicating when I got home after resetting it everything is working correctly now for me.
